### ISSUE TITLE
How to use devkitPro/libnds in config

### ISSUE THREAD

**Issue by axel7083** [Overblade/fireflower#3]
I have installed devkitpro on my machine, but I can't find how to use it since it is using Msys2.
Is there a way to use it ?

**Comment by TheGameratorT** [comment]
libnds is usually used for creating games so I strongly advise you not to use when patching games, most of the times you will be better by just using most SDK functions that can be found in the game you wish to patch.
While Fireflower does allow adding extra include paths in the .json file it doesn't allow linking against external libraries apart from libgcc.
If you want try NCPatcher it aims to continue this tool's legacy.
